export const GET_COUNTRIES = "GET_COUNTRIES";
export const FILTER_CONTINENTS = "GET_CONTINENTS";
export const ORDER_BY_ALPHABETIC = "ORDER_BY_ALPHABETIC";
export const ACTUAL_PAGE_COLOR = "ACTUAL_PAGE_COLOR";
export const SEARCH_COUNTRY_BY_NAME = "SEARCH_COUNTRY_BY_NAME";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
